# -*- coding: utf-8 -*-
"""BTC-USD .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtvPv5VUtGybVoSJ7n5evF5NUg4cv915
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

btc = yf.download('BTC-USD', period='5y', interval='1d')

prices = btc['Close']

spread_days = 182
shifted_prices = prices.shift(spread_days)

spread = prices - shifted_prices

spread = spread.dropna()

plt.figure(figsize=(12, 6))
plt.plot(spread.index, spread, label='6-month BTC-USD Spread', color='dodgerblue')
plt.axhline(0, color='gray', linestyle='--', linewidth=1)
plt.title('6-Month BTC-USD Spread Over Time')
plt.xlabel('Date')
plt.ylabel('Spread (USD)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

